version: "3.9"
services:
  posts:
    container_name: supergram-posts
    # image: neeejm/supergram-posts:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    env_file:
      - .env.docker

  db:
    container_name: supergram-mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env.docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}