spring:
  config:
    import: 'optional:file:.env[.properties]'

  output:
    ansi:
      enabled: always

  banner:
    location: 'banner.txt'

  data:
    mongodb:
      authentication-database: ${DB_AUTH_DB}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_NAME}
      port: 27017
      host: ${DB_HOST}

server:
  servlet:
    context-path: /api/v1

  port: ${PORT}


logging:
  level:
    '[org.springframework.web.filter.CommonsRequestLoggingFilter]': 'DEBUG'
    '[com.neeejm.posts]': 'DEBUG'


spring.output.ansi.enabled: always