spring:
  config:
    import: 'optional:file:.env[.properties]'

  output:
    ansi:
      enabled: always

  banner:
    location: 'banner.txt'

  data:
    mongodb:
      uri: ${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?authSource=${DB_AUTH_DB}&retryWrites=true&w=majority"

server:
  servlet:
    context-path: /api/v1

  port: ${PORT:8080}


logging:
  level:
    '[org.springframework.web.filter.CommonsRequestLoggingFilter]': 'DEBUG'
    '[com.neeejm.posts]': 'DEBUG'


spring.output.ansi.enabled: always