spring:
  config:
    import: 'optional:file:.env[.properties]'

  output:
    ansi:
      enabled: always

  banner:
    location: 'banner.txt'

  data:
    mongodb:
      # authentication-database: test
      # username: supergramAdmin
      # password: admin
      database: ${DB_NAME}
      # port: 27017
      # host: localhost

server:
  servlet:
    context-path: /api/v1

  port: ${SERVER_PORT}


logging:
  level:
    '[org.springframework.web.filter.CommonsRequestLoggingFilter]': 'DEBUG'
    '[com.neeejm.posts]': 'DEBUG'


spring.output.ansi.enabled: always