name: Posts - CI

on:
  push:
    branches: [main]
    paths:
      - "apps/posts/**"

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Change to posts dir
        run: cd ./"apps/posts/"

      - name: Make gradlew executable
        run: chmod +x gradlew
    
      - name: Build source
        run: ./gradlew clean build -x test

      - name: Unit Test
        run: ./gradlew clean unitTest

      - name: Cache build dir
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ hashFiles('settings.gradle') }}-build

      - name: Code Analysis
        run: ./gradlew sonarqube
        env:
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  test-env:
    name: Test Environment
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Integration Test
        run: ./gradlew clean integrationTest