name: Posts - CI

on:
  push:
    branches: [main]
    paths:
      - "apps/posts/**"

  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/posts/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew
    
      - name: Build source
        working-directory: apps/posts/
        run: ./gradlew clean build -x test

      - name: Unit Test
        run: ./gradlew clean unitTest

      - name: Cache build dir
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ hashFiles('settings.gradle') }}-build

      - name: Code Analysis
        run: ./gradlew sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-env:
    name: Test Environment
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: apps/posts/
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Integration Test
        run: ./gradlew clean integrationTest
  
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/posts/
    needs: [test-env]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: echo ls
        run: ls -l

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: neeejm/supergram-posts:latest